# Минимальный конфиг для dev-окружения.
# В проде стоит пересмотреть persistence-стратегию и добавить пароль (requirepass).

bind 0.0.0.0
protected-mode no
port 6379

# Персистентность: RDB-снапшоты, volume уже подключён в docker-compose.yml
save 900 1
save 300 10
save 60 10000

dir /data
appendonly no
